FROM thenatureofsoftware/alpine-arm64:latest

MAINTAINER https://github.com/larmog

ENV HOME=/app

COPY .work/mc-arm64 /usr/local/bin/mc
COPY mc-mirror /app/mc-mirror
COPY .work/qemu-aarch64-static /usr/bin/qemu-aarch64-static
COPY config-mc.json /app/config/config.json

RUN mkdir /app/source && mkdir /app/target

VOLUME /source
VOLUME /target
VOLUME /app/config

ENTRYPOINT ["/app/mc-mirror"]

CMD ["/app/source", "/app/target"]
