FROM scratch

MAINTAINER https://github.com/larmog

COPY minio /minio
COPY config-minio.json /app/config/config.json

VOLUME ["/export"]

EXPOSE 9000
ENTRYPOINT ["/minio", "-C", "/app/config"]

CMD ["version"]
