FROM hypriot/rpi-alpine

MAINTAINER https://github.com/larmog

ENV HOME=/app

COPY .work/mc-arm /usr/local/bin/mc
COPY mc-mirror /app/mc-mirror
COPY .work/qemu-arm-static /usr/bin/qemu-arm-static
COPY config-mc.json /app/config/config.json

RUN mkdir /app/source && mkdir /app/target

VOLUME /source
VOLUME /target
VOLUME /app/config

ENTRYPOINT ["/app/mc-mirror"]

CMD ["/app/source", "/app/target"]
