FROM scratch

MAINTAINER https://github.com/larmog

COPY .work/qemu-arm-static /usr/bin/qemu-arm-static
COPY .work/mc-arm /mc

COPY config-mc.json /app/config/config.json

VOLUME /app/config

ENTRYPOINT ["/mc", "--quiet", "-C", "/app/config"]
