FROM scratch

MAINTAINER https://github.com/larmog

COPY .work/qemu-aarch64-static /usr/bin/qemu-aarch64-static
COPY .work/minio-arm64 /minio
COPY config-minio.json /app/config/config.json

VOLUME ["/export"]

EXPOSE 9000
ENTRYPOINT ["/minio", "-C", "/app/config"]

CMD ["version"]
