FROM scratch

MAINTAINER https://github.com/larmog

COPY .work/qemu-arm-static /usr/bin/qemu-arm-static
COPY .work/minio-arm /minio
COPY config-minio.json /app/config/config.json

VOLUME ["/export"]

EXPOSE 9000
ENTRYPOINT ["/minio", "-C", "/app/config"]

CMD ["version"]
