#!/bin/sh

if [ "$1" == "" ]; then
  echo "no source set"
  exit 1
fi

if [ "$2" == "" ]; then
  echo "no target set"
  exit 1
fi

SOURCE=${SOURCE:-$(echo $1)}
TARGET=${TARGET:-$(echo $2)}
WAIT_TIME=${WAIT_TIME:-3}
STOP=0

trap ctrl_c INT

function ctrl_c() {
  echo " CTRL-C stopping..."
  STOP=1
}

echo "mc-mirror mirroring from $SOURCE to $TARGET"
touch /app/timestamp

while [ true ]; do
  if [ $STOP -eq 1 ]; then
    echo "mc-mirror stopped"
    exit 0
  else
    sleep $WAIT_TIME
  fi

  for file in $(find $SOURCE -type f -newer /app/timestamp);
  do
    mc --quiet --no-color -C /app/config cp $file ${TARGET}${file#$SOURCE}
    touch $file
  done
  mc --quiet --no-color -C /app/config mirror --remove --force $SOURCE $TARGET
  touch /app/timestamp
done
